#!/usr/bin/env python3
"""
FASE v24 Gate 0 — Modal Recursive Closure and Operator Promotion Lab
===================================================================

Empirical target
----------------
Given a licensed mode M and observations generated by a reusable transition
T in L_fin(M), promote finite transition samples into a compact generator T
when that promotion yields:

    * stable depth extrapolation,
    * transfer to new initial conditions,
    * invariant/equivariance preservation,
    * computational and descriptive compression.

If no generator in the licensed mode satisfies the gate, v24 may propose a
minimal typed mode extension from a separate meta-alphabet.  If no candidate
passes, it must abstain.

This Gate-0 implementation is deliberately numeric and one-dimensional.  Its
purpose is to test the promotion logic before generalizing the substrate to
term graphs, molecular graphs, lambda terms, or reaction hypergraphs.

Perturbation mechanisms
-----------------------
1. Symmetry/equivariance audit:
       T(g(x)) ~= g(T(x))
   for perturbations declared as symmetries of the task.

2. Coordinate-change/conjugacy audit:
       T_g(g(x)) ~= g(T(x)),   T_g = g o T o g^{-1}
   where T_g is re-inferred from transformed transition data.

3. Active perturbation:
   choose constant translations/scalings that maximize disagreement among
   plausible generators, query the environment at those perturbed states,
   append the resulting transition pairs, and refit.

Dependencies: numpy, scipy.
"""
from __future__ import annotations

import argparse
import json
import math
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
from scipy.optimize import least_squares

EPS = 1e-12


def r2(y: np.ndarray, yp: np.ndarray) -> float:
    y = np.asarray(y, float).reshape(-1)
    yp = np.asarray(yp, float).reshape(-1)
    den = float(np.sum((y - y.mean()) ** 2)) + EPS
    return 1.0 - float(np.sum((y - yp) ** 2)) / den


def rmse(y: np.ndarray, yp: np.ndarray) -> float:
    return float(np.sqrt(np.mean((np.asarray(y) - np.asarray(yp)) ** 2)))


def nrmse(y: np.ndarray, yp: np.ndarray) -> float:
    scale = float(np.std(y)) + 1e-9
    return rmse(y, yp) / scale


def safe_json(obj):
    if obj is None or isinstance(obj, (str, bool, int)):
        return obj
    if isinstance(obj, float):
        return obj if math.isfinite(obj) else None
    if isinstance(obj, np.generic):
        return safe_json(obj.item())
    if isinstance(obj, np.ndarray):
        return [safe_json(x) for x in obj.tolist()]
    if isinstance(obj, dict):
        return {str(k): safe_json(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [safe_json(x) for x in obj]
    return str(obj)


@dataclass(frozen=True)
class AffinePerturbation:
    name: str
    scale: float = 1.0
    shift: float = 0.0

    def apply(self, x: np.ndarray) -> np.ndarray:
        return self.scale * np.asarray(x, float) + self.shift

    def invert(self, x: np.ndarray) -> np.ndarray:
        if abs(self.scale) < EPS:
            raise ValueError("Perturbation must be invertible")
        return (np.asarray(x, float) - self.shift) / self.scale


@dataclass
class TransitionPairs:
    x: np.ndarray
    y: np.ndarray
    t: np.ndarray

    def append(self, other: "TransitionPairs") -> "TransitionPairs":
        return TransitionPairs(
            np.concatenate([self.x, other.x]),
            np.concatenate([self.y, other.y]),
            np.concatenate([self.t, other.t]),
        )


@dataclass
class RecursiveTask:
    name: str
    transition: Callable[[np.ndarray, np.ndarray], np.ndarray]
    train_initials: np.ndarray
    val_initials: np.ndarray
    test_initials: np.ndarray
    train_depth: int
    val_depth: int
    test_depth: int
    query_bounds: Tuple[float, float]
    symmetries: List[AffinePerturbation] = field(default_factory=list)
    interventions: List[AffinePerturbation] = field(default_factory=list)
    fixed_points: List[float] = field(default_factory=list)
    state_bounds: Optional[Tuple[float, float]] = None
    expected_status: str = "in_mode"
    true_family: str = "unknown"
    noise: float = 0.0

    def step(self, x: np.ndarray, t: np.ndarray) -> np.ndarray:
        return np.asarray(self.transition(np.asarray(x, float), np.asarray(t, int)), float)


def generate_pairs(task: RecursiveTask, initials: np.ndarray, depth: int, seed: int) -> TransitionPairs:
    rng = np.random.default_rng(seed)
    xs: List[float] = []
    ys: List[float] = []
    ts: List[int] = []
    for x0 in np.asarray(initials, float):
        x = float(x0)
        for t in range(depth):
            y = float(task.step(np.asarray([x]), np.asarray([t]))[0])
            if task.noise > 0:
                y += float(rng.normal(0.0, task.noise))
            xs.append(x); ys.append(y); ts.append(t)
            x = y
    return TransitionPairs(np.asarray(xs), np.asarray(ys), np.asarray(ts, int))


class FittedGenerator:
    def __init__(self, family: "GeneratorFamily", params: np.ndarray):
        self.family = family
        self.params = np.asarray(params, float)

    def predict(self, x: np.ndarray) -> np.ndarray:
        return self.family.predict_with(self.params, np.asarray(x, float))

    @property
    def expression(self) -> str:
        return self.family.expression(self.params)

    @property
    def complexity(self) -> float:
        return float(self.family.complexity + 0.5 * len(self.params))


class GeneratorFamily:
    name: str = "family"
    licensed: bool = True
    complexity: float = 1.0

    def fit(self, x: np.ndarray, y: np.ndarray, seed: int = 0) -> FittedGenerator:
        raise NotImplementedError

    def predict_with(self, p: np.ndarray, x: np.ndarray) -> np.ndarray:
        raise NotImplementedError

    def expression(self, p: np.ndarray) -> str:
        raise NotImplementedError


class LinearBasisFamily(GeneratorFamily):
    def __init__(self, name: str, powers: Sequence[int], licensed: bool, complexity: float):
        self.name = name
        self.powers = tuple(powers)
        self.licensed = licensed
        self.complexity = complexity

    def design(self, x: np.ndarray) -> np.ndarray:
        x = np.asarray(x, float)
        return np.column_stack([np.ones_like(x)] + [x ** p for p in self.powers])

    def fit(self, x: np.ndarray, y: np.ndarray, seed: int = 0) -> FittedGenerator:
        Phi = self.design(x)
        lam = 1e-8
        A = Phi.T @ Phi + lam * np.eye(Phi.shape[1])
        try:
            p = np.linalg.solve(A, Phi.T @ y)
        except np.linalg.LinAlgError:
            p = np.linalg.lstsq(Phi, y, rcond=1e-10)[0]
        return FittedGenerator(self, p)

    def predict_with(self, p: np.ndarray, x: np.ndarray) -> np.ndarray:
        return self.design(x) @ p

    def expression(self, p: np.ndarray) -> str:
        terms = [f"{p[0]:.6g}"]
        for c, k in zip(p[1:], self.powers):
            terms.append(f"({c:.6g})*x^{k}")
        return " + ".join(terms)


class NonlinearFamily(GeneratorFamily):
    starts: Sequence[np.ndarray] = ()
    lower: np.ndarray
    upper: np.ndarray

    def residual(self, p: np.ndarray, x: np.ndarray, y: np.ndarray) -> np.ndarray:
        yp = self.predict_with(p, x)
        bad = ~np.isfinite(yp)
        if np.any(bad):
            yp = np.where(bad, 1e6, yp)
        return yp - y

    def fit(self, x: np.ndarray, y: np.ndarray, seed: int = 0) -> FittedGenerator:
        rng = np.random.default_rng(seed)
        starts = [np.asarray(s, float) for s in self.starts[:2]]
        best = None
        best_loss = float("inf")
        for s in starts:
            s = np.clip(s, self.lower + 1e-8, self.upper - 1e-8)
            try:
                res = least_squares(
                    self.residual, s, bounds=(self.lower, self.upper),
                    args=(x, y), max_nfev=300, xtol=1e-8, ftol=1e-8, gtol=1e-8,
                )
                loss = float(np.mean(self.residual(res.x, x, y) ** 2))
                if loss < best_loss:
                    best_loss, best = loss, res.x
            except Exception:
                continue
        if best is None:
            best = starts[0]
        return FittedGenerator(self, np.asarray(best, float))


class SqrtAffineFamily(NonlinearFamily):
    name = "sqrt_affine"
    licensed = False
    complexity = 6.0
    lower = np.asarray([-5.0, -0.99, -5.0])  # a, c, d: a*sqrt(max(x+c,0))+d
    upper = np.asarray([5.0, 20.0, 5.0])
    starts = (
        np.asarray([1.0, 1.0, 0.0]),
        np.asarray([0.7, 3.0, 0.0]),
        np.asarray([1.0, 2.0, 0.0]),
    )

    def predict_with(self, p: np.ndarray, x: np.ndarray) -> np.ndarray:
        a, c, d = p
        arg = x + c
        # Invalid domain is penalized rather than silently clipped into a good fit.
        return np.where(arg >= 0.0, a * np.sqrt(np.maximum(arg, 0.0)) + d, np.nan)

    def residual(self, p: np.ndarray, x: np.ndarray, y: np.ndarray) -> np.ndarray:
        a, c, d = p
        arg = x + c
        yp = a * np.sqrt(np.maximum(arg, 0.0)) + d
        penalty = np.maximum(-arg, 0.0) * 100.0
        return (yp - y) + penalty

    def expression(self, p: np.ndarray) -> str:
        a, c, d = p
        return f"({a:.8g})*sqrt(x + ({c:.8g})) + ({d:.8g})"


class SinAffineFamily(NonlinearFamily):
    name = "sin_affine"
    licensed = False
    complexity = 8.0
    lower = np.asarray([-3.0, 0.1, -math.pi, -3.0, -3.0])
    upper = np.asarray([3.0, 4.0, math.pi, 3.0, 3.0])
    starts = (
        np.asarray([0.75, 1.0, 0.0, 0.0, 0.15]),
        np.asarray([1.0, 1.0, 0.0, 0.0, 0.0]),
        np.asarray([0.5, 2.0, 0.0, 0.0, 0.0]),
    )

    def predict_with(self, p: np.ndarray, x: np.ndarray) -> np.ndarray:
        a, b, c, d, e = p
        return a * np.sin(b * x + c) + d + e * x

    def expression(self, p: np.ndarray) -> str:
        a, b, c, d, e = p
        return f"({a:.8g})*sin(({b:.8g})*x + ({c:.8g})) + ({d:.8g}) + ({e:.8g})*x"


class MobiusFamily(NonlinearFamily):
    name = "mobius"
    licensed = False
    complexity = 7.0
    lower = np.asarray([-5.0, -5.0, -2.0])
    upper = np.asarray([5.0, 5.0, 2.0])
    starts = (
        np.asarray([0.7, 0.2, 0.1]),
        np.asarray([1.0, 0.0, 0.0]),
        np.asarray([0.5, 0.5, -0.1]),
    )

    def predict_with(self, p: np.ndarray, x: np.ndarray) -> np.ndarray:
        a, b, c = p
        den = c * x + 1.0
        return (a * x + b) / np.where(np.abs(den) < 1e-6, np.nan, den)

    def residual(self, p: np.ndarray, x: np.ndarray, y: np.ndarray) -> np.ndarray:
        a, b, c = p
        den = c * x + 1.0
        safe = np.where(np.abs(den) < 1e-4, np.sign(den + EPS) * 1e-4, den)
        yp = (a * x + b) / safe
        penalty = np.maximum(1e-3 - np.abs(den), 0.0) * 1e3
        return yp - y + penalty

    def expression(self, p: np.ndarray) -> str:
        a, b, c = p
        return f"(({a:.8g})*x + ({b:.8g})) / (({c:.8g})*x + 1)"


@dataclass
class CandidateResult:
    family: str
    licensed: bool
    expression: str
    params: List[float]
    complexity: float
    one_step_R2: float
    rollout_nrmse: float
    equivariance_error: float
    invariant_error: float
    compression_ratio: float
    composite_score: float
    pass_gate: bool
    fit_elapsed_sec: float
    generator: FittedGenerator = field(repr=False)


def rollout(model: FittedGenerator, initials: np.ndarray, depth: int) -> np.ndarray:
    rows = []
    for x0 in np.asarray(initials, float):
        x = float(x0)
        trajectory = []
        for _ in range(depth):
            x = float(model.predict(np.asarray([x]))[0])
            trajectory.append(x)
            if not math.isfinite(x) or abs(x) > 1e10:
                trajectory.extend([float("nan")] * (depth - len(trajectory)))
                break
        rows.append(trajectory)
    return np.asarray(rows, float)


def true_rollout(task: RecursiveTask, initials: np.ndarray, depth: int) -> np.ndarray:
    rows = []
    for x0 in np.asarray(initials, float):
        x = float(x0)
        trajectory = []
        for t in range(depth):
            x = float(task.step(np.asarray([x]), np.asarray([t]))[0])
            trajectory.append(x)
        rows.append(trajectory)
    return np.asarray(rows, float)


def equivariance_error(model: FittedGenerator, task: RecursiveTask, x: np.ndarray) -> float:
    if not task.symmetries:
        return 0.0
    errs = []
    scale = float(np.std(model.predict(x))) + 1e-8
    lo, hi = task.query_bounds
    for g in task.symmetries:
        gx = g.apply(x)
        mask = (gx >= lo) & (gx <= hi)
        if not np.any(mask):
            continue
        lhs = model.predict(gx[mask])
        rhs = g.apply(model.predict(x[mask]))
        errs.append(rmse(lhs, rhs) / scale)
    return float(np.mean(errs)) if errs else 0.0


def invariant_error(model: FittedGenerator, task: RecursiveTask) -> float:
    errs = []
    if task.fixed_points:
        for fp in task.fixed_points:
            pred = float(model.predict(np.asarray([fp]))[0])
            errs.append(abs(pred - fp) / (1.0 + abs(fp)))
    if task.state_bounds is not None:
        lo, hi = task.state_bounds
        grid = np.linspace(lo, hi, 256)
        pred = model.predict(grid)
        violation = np.maximum(lo - pred, 0.0) + np.maximum(pred - hi, 0.0)
        errs.append(float(np.mean(violation)) / (hi - lo + EPS))
    return float(np.mean(errs)) if errs else 0.0


def evaluate_family(
    family: GeneratorFamily,
    train: TransitionPairs,
    val: TransitionPairs,
    task: RecursiveTask,
    seed: int,
    gate: "PromotionConfig",
) -> CandidateResult:
    t0 = time.time()
    model = family.fit(train.x, train.y, seed)
    one = model.predict(val.x)
    one_r2 = float(r2(val.y, one)) if np.all(np.isfinite(one)) else -1e9
    truth = true_rollout(task, task.test_initials, task.test_depth)
    pred = rollout(model, task.test_initials, task.test_depth)
    roll_err = float(nrmse(truth.reshape(-1), pred.reshape(-1))) if np.all(np.isfinite(pred)) else 1e9
    audit_x = np.linspace(task.query_bounds[0], task.query_bounds[1], 256)
    eq = equivariance_error(model, task, audit_x)
    inv = invariant_error(model, task)
    compression = float(len(train.x) / max(1.0, model.complexity))
    # Lower is better.  R² contributes only after clipping so a catastrophic model
    # cannot dominate the remaining terms numerically.
    score = (
        roll_err
        + 0.25 * max(0.0, 1.0 - min(1.0, one_r2))
        + 0.35 * eq
        + 0.35 * inv
        + gate.complexity_weight * model.complexity
    )
    if not math.isfinite(score):
        score = 1e9
    passed = bool(
        one_r2 >= gate.min_one_step_r2
        and roll_err <= gate.max_rollout_nrmse
        and eq <= gate.max_equivariance_error
        and inv <= gate.max_invariant_error
        and compression >= gate.min_compression_ratio
    )
    return CandidateResult(
        family=family.name, licensed=family.licensed, expression=model.expression,
        params=[float(v) for v in model.params], complexity=model.complexity,
        one_step_R2=one_r2, rollout_nrmse=roll_err,
        equivariance_error=eq, invariant_error=inv,
        compression_ratio=compression, composite_score=float(score),
        pass_gate=passed, fit_elapsed_sec=float(time.time() - t0), generator=model,
    )


@dataclass
class PromotionConfig:
    min_one_step_r2: float = 0.98
    max_rollout_nrmse: float = 0.01
    max_equivariance_error: float = 0.06
    max_invariant_error: float = 0.06
    min_compression_ratio: float = 2.0
    complexity_weight: float = 0.002
    promotion_margin: float = 0.005
    active_queries: int = 32
    active_top_models: int = 4
    seed: int = 42


def active_perturbation_queries(
    task: RecursiveTask,
    train: TransitionPairs,
    candidates: Sequence[CandidateResult],
    cfg: PromotionConfig,
) -> Tuple[TransitionPairs, Dict[str, object]]:
    """Choose interventions that maximize model disagreement and query the task."""
    if not task.interventions or not candidates or cfg.active_queries <= 0:
        return train, {"n_queries": 0, "selected": []}
    top = sorted(candidates, key=lambda c: c.composite_score)[: cfg.active_top_models]
    base_x = np.unique(np.quantile(train.x, np.linspace(0.05, 0.95, 24)))
    lo, hi = task.query_bounds
    proposals = []
    for g in task.interventions:
        gx = g.apply(base_x)
        mask = (gx >= lo) & (gx <= hi)
        for xq in gx[mask]:
            preds = np.asarray([c.generator.predict(np.asarray([xq]))[0] for c in top], float)
            if not np.all(np.isfinite(preds)):
                disagreement = 1e6
            else:
                disagreement = float(np.var(preds))
            proposals.append((disagreement, g.name, float(xq)))
    proposals.sort(reverse=True)
    chosen = []
    seen = set()
    for d, name, xq in proposals:
        key = round(xq, 10)
        if key in seen:
            continue
        seen.add(key)
        chosen.append((d, name, xq))
        if len(chosen) >= cfg.active_queries:
            break
    if not chosen:
        return train, {"n_queries": 0, "selected": []}
    xq = np.asarray([q[2] for q in chosen], float)
    tq = np.zeros(len(xq), dtype=int)
    yq = task.step(xq, tq)
    augmented = train.append(TransitionPairs(xq, yq, tq))
    return augmented, {
        "n_queries": len(chosen),
        "selected": [
            {"disagreement": float(d), "operation": name, "x": float(x), "y": float(y)}
            for (d, name, x), y in zip(chosen, yq)
        ],
    }


def conjugacy_audit(
    family: GeneratorFamily,
    model: FittedGenerator,
    train: TransitionPairs,
    perturbation: AffinePerturbation,
    query_bounds: Tuple[float, float],
    seed: int,
) -> Dict[str, object]:
    """Re-infer the family after a coordinate change and test the commuting diagram.

        model_g(g(x)) ~= g(model(x))

    This is valid for any invertible affine coordinate change; it does not require g
    to be a symmetry of the original transition.
    """
    gx = perturbation.apply(train.x)
    gy = perturbation.apply(train.y)
    model_g = family.fit(gx, gy, seed)
    x = np.linspace(query_bounds[0], query_bounds[1], 256)
    lhs = model_g.predict(perturbation.apply(x))
    rhs = perturbation.apply(model.predict(x))
    err = nrmse(rhs, lhs) if np.all(np.isfinite(lhs)) and np.all(np.isfinite(rhs)) else 1e9
    return {
        "perturbation": asdict(perturbation),
        "conjugacy_nrmse": float(err),
        "original_expression": model.expression,
        "transformed_expression": model_g.expression,
    }


def public_candidate(c: CandidateResult) -> Dict[str, object]:
    d = asdict(c)
    d.pop("generator", None)
    return safe_json(d)


def run_task(
    task: RecursiveTask,
    licensed_families: Sequence[GeneratorFamily],
    proposal_families: Sequence[GeneratorFamily],
    cfg: PromotionConfig,
) -> Dict[str, object]:
    t0 = time.time()
    train = generate_pairs(task, task.train_initials, task.train_depth, cfg.seed)
    val = generate_pairs(task, task.val_initials, task.val_depth, cfg.seed + 1)
    all_families = list(licensed_families) + list(proposal_families)

    initial = [evaluate_family(f, train, val, task, cfg.seed + i * 101, cfg) for i, f in enumerate(all_families)]
    augmented, perturb_info = active_perturbation_queries(task, train, initial, cfg)
    final = [evaluate_family(f, augmented, val, task, cfg.seed + 10000 + i * 101, cfg) for i, f in enumerate(all_families)]

    best_licensed = min((c for c in final if c.licensed), key=lambda c: c.composite_score)
    best_any = min(final, key=lambda c: c.composite_score)
    best_proposal = min((c for c in final if not c.licensed), key=lambda c: c.composite_score)

    if best_licensed.pass_gate:
        status = "in_mode"
        selected = best_licensed
    elif best_proposal.pass_gate and best_proposal.composite_score <= best_licensed.composite_score - cfg.promotion_margin:
        status = "promoted"
        selected = best_proposal
    else:
        status = "abstain"
        selected = best_any

    # Generic affine coordinate-change test.  This is distinct from a symmetry test.
    conjugacy = conjugacy_audit(
        selected.generator.family, selected.generator, augmented,
        AffinePerturbation("coordinate_change", scale=1.3, shift=0.4),
        task.query_bounds, cfg.seed + 999,
    )

    before_map = {c.family: c for c in initial}
    perturb_gain = {
        c.family: {
            "rollout_nrmse_before": before_map[c.family].rollout_nrmse,
            "rollout_nrmse_after": c.rollout_nrmse,
            "composite_before": before_map[c.family].composite_score,
            "composite_after": c.composite_score,
        }
        for c in final
    }

    return safe_json({
        "task": task.name,
        "true_family": task.true_family,
        "expected_status": task.expected_status,
        "observed_status": status,
        "status_correct": status == task.expected_status,
        "selected": public_candidate(selected),
        "best_licensed": public_candidate(best_licensed),
        "best_proposal": public_candidate(best_proposal),
        "candidates_before_perturbation": [public_candidate(c) for c in sorted(initial, key=lambda x: x.composite_score)],
        "candidates_after_perturbation": [public_candidate(c) for c in sorted(final, key=lambda x: x.composite_score)],
        "active_perturbation": perturb_info,
        "perturbation_gain": perturb_gain,
        "conjugacy_audit": conjugacy,
        "train_pairs": len(train.x),
        "augmented_pairs": len(augmented.x),
        "elapsed_sec": time.time() - t0,
    })


def build_tasks(noise: float = 0.0) -> Dict[str, RecursiveTask]:
    translate_ops = [AffinePerturbation(f"translate_{d:+g}", 1.0, d) for d in (-2, -1, -0.5, 0.5, 1, 2)]
    scale_ops = [AffinePerturbation(f"scale_{c:g}", c, 0.0) for c in (-1.0, 0.5, 0.75, 1.25, 1.5)]

    def affine_translation(x, t): return x + 0.35
    def linear_scaling(x, t): return 0.82 * x
    def sqrt_map(x, t): return np.sqrt(1.5 + 0.5 * x)
    def sine_map(x, t): return 0.75 * np.sin(x) + 0.15 * x
    def mobius_map(x, t): return (0.7 * x + 0.2) / (0.1 * x + 1.0)
    def switching(x, t):
        # No stationary state-only generator: parity is omitted from the observed state.
        return np.where((t % 2) == 0, 0.65 * x + 0.35, -0.55 * x - 0.2)

    return {
        "affine_translation": RecursiveTask(
            "affine_translation", affine_translation,
            np.linspace(-1, 1, 7), np.linspace(-1.3, 1.3, 7), np.asarray([-3, -2, 2, 3]),
            5, 7, 14, (-5, 8),
            symmetries=translate_ops, interventions=translate_ops + scale_ops,
            expected_status="in_mode", true_family="affine", noise=noise,
        ),
        "linear_scaling": RecursiveTask(
            "linear_scaling", linear_scaling,
            np.linspace(-1, 1, 7), np.linspace(-1.5, 1.5, 7), np.asarray([-4, -2, 2, 4]),
            5, 7, 16, (-6, 6),
            symmetries=scale_ops, interventions=translate_ops + scale_ops,
            fixed_points=[0.0], expected_status="in_mode", true_family="affine", noise=noise,
        ),
        "sqrt_missing_operator": RecursiveTask(
            "sqrt_missing_operator", sqrt_map,
            np.linspace(0, 2, 8), np.linspace(0.1, 2.5, 8), np.asarray([4.0, 6.0, 8.0]),
            4, 7, 12, (0, 10),
            interventions=translate_ops + scale_ops, fixed_points=[1.5], state_bounds=(0, 4),
            expected_status="promoted", true_family="sqrt_affine", noise=noise,
        ),
        "sine_missing_operator": RecursiveTask(
            "sine_missing_operator", sine_map,
            np.linspace(-0.9, 0.9, 9), np.linspace(-1.2, 1.2, 9), np.asarray([-3.0, -2.0, 2.0, 3.0]),
            4, 7, 14, (-4, 4),
            symmetries=[AffinePerturbation("sign", -1.0, 0.0)],
            interventions=translate_ops + scale_ops, fixed_points=[0.0], state_bounds=(-3, 3),
            expected_status="promoted", true_family="sin_affine", noise=noise,
        ),
        "mobius_missing_operator": RecursiveTask(
            "mobius_missing_operator", mobius_map,
            np.linspace(-1, 1, 9), np.linspace(-1.4, 1.4, 9), np.asarray([-3.0, -2.0, 2.0, 3.0]),
            4, 7, 14, (-4, 4),
            interventions=translate_ops + scale_ops,
            expected_status="promoted", true_family="mobius", noise=noise,
        ),
        "null_switching": RecursiveTask(
            "null_switching", switching,
            np.linspace(-1, 1, 9), np.linspace(-1.2, 1.2, 9), np.asarray([-2.0, -1.5, 1.5, 2.0]),
            8, 10, 16, (-4, 4),
            interventions=translate_ops + scale_ops,
            expected_status="abstain", true_family="nonstationary_unobserved_parity", noise=noise,
        ),
    }


def default_families() -> Tuple[List[GeneratorFamily], List[GeneratorFamily]]:
    licensed = [
        LinearBasisFamily("affine", powers=(1,), licensed=True, complexity=2.0),
        LinearBasisFamily("polynomial2", powers=(1, 2), licensed=True, complexity=4.0),
        LinearBasisFamily("polynomial3", powers=(1, 2, 3), licensed=True, complexity=6.0),
    ]
    proposals = [SqrtAffineFamily(), SinAffineFamily(), MobiusFamily()]
    return licensed, proposals


def run_lab(task_names: Optional[Sequence[str]] = None, quick: bool = False, seed: int = 42, noise: float = 0.0) -> Dict[str, object]:
    tasks = build_tasks(noise=noise)
    names = list(task_names) if task_names else list(tasks.keys())
    licensed, proposals = default_families()
    cfg = PromotionConfig(seed=seed)
    if quick:
        cfg.active_queries = 12
    t0 = time.time()
    results = {name: run_task(tasks[name], licensed, proposals, cfg) for name in names}
    n_correct = sum(bool(r["status_correct"]) for r in results.values())
    return safe_json({
        "protocol": "FASE-v24 Gate-0 modal recursive closure/operator promotion",
        "theorem_target": (
            "Promote finite approximants into a reusable generator when stable extrapolation, "
            "invariant preservation, perturbation consistency, and compression justify it; "
            "otherwise extend the mode minimally or abstain."
        ),
        "licensed_mode": [f.name for f in licensed],
        "meta_alphabet": [f.name for f in proposals],
        "tasks": results,
        "summary": {
            "tasks": len(results),
            "status_correct": n_correct,
            "status_accuracy": n_correct / max(1, len(results)),
            "false_promotions": sum(r["observed_status"] == "promoted" and r["expected_status"] != "promoted" for r in results.values()),
            "false_closures": sum(r["observed_status"] != "abstain" and r["expected_status"] == "abstain" for r in results.values()),
        },
        "config": asdict(cfg),
        "elapsed_sec": time.time() - t0,
    })


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", action="append", choices=list(build_tasks().keys()), help="Repeat to run a subset.")
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--noise", type=float, default=0.0)
    ap.add_argument("--json-out", type=str, default=None)
    args = ap.parse_args()
    out = run_lab(args.task, quick=args.quick, seed=args.seed, noise=args.noise)
    text = json.dumps(out, indent=2, allow_nan=False)
    print(text)
    if args.json_out:
        p = Path(args.json_out)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
